name: Playwright Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Install Playwright Browsers
        run: dotnet new tool-manifest

      - name: Install
        run: dotnet add package Microsoft.Playwright.CLI
        
      - name: Manifest
        run: dotnet playwright install
        
      - name: Run tests
        run: dotnet test --configuration Release --no-build
